version: "3.7"

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: sample_db_name
      MONGO_INITDB_COLLECTION: sample_collections
    ports:
      - 27017:27017
    volumes:
      - ./mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - dbdata:/data/db
      - configdb:/data/configdb

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_SERVER: mongo
    depends_on:
      - mongo

  ruby-app:
    build:
      context: .
      dockerfile: ./api/Dockerfile
    environment:
      MONGODB_HOST_NAME: mongo:27017
      MONGODB_NAME: sample_db_name
      MONGODB_ADMINUSERNAME: root
      MONGODB_ADMINPASSWORD: example
    volumes:
      - gem-data:/usr/local/bundle
      - ./api/script:/api/script
    depends_on:
      - mongo

volumes:
  dbdata:
  configdb:
  gem-data:
